apiVersion: v1
data:
  config: |+
    [mysqld]
    pid-file                = /run/mysqld/mysqld.pid
    basedir                 = /usr
    datadir                 = /var/lib/mysql/data
    tmpdir                  = /tmp
    lc-messages-dir         = /usr/share/mysql
    lc-messages             = en_US
    skip-external-locking
    expire_logs_days        = 10
    character-set-server  = utf8mb4
    collation-server      = utf8mb4_general_ci

kind: ConfigMap
metadata:
  name: test-database-deployment-config
  namespace: test-namespace
