apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-database-deployment
  namespace: test-namespace
  labels:
    app: test
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      component: database
  template:
    metadata:
      labels:
        app: test
        component: database
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test-database-data-claim
        - name: config
          configMap:
            name: test-database-deployment-config
      containers:
        - name: test-database
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
          volumeMounts:
            - name: data
              mountPath: "/var/lib/mysql"
            - name: config
              mountPath: "/etc/mysql/mariadb.conf.d/50-server.cnf"
                items:
                  - key: config
                    path: "50-server.cnf"
