apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test-namespace
  name: test-database-data-claim
spec:
  storageClassName: tests-nfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
