apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    component: backend
  name: test-backend-service
  namespace: test-namespace
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: test
    component: backend
  type: ClusterIP

